@AspNetCoreIdentity_HostAddress = http://localhost:5000
@email = nguyentrucxjnh@gmail.com

# securedEndpoint
# @name weatherforecastCookie
GET {{AspNetCoreIdentity_HostAddress}}/weatherforecast/
Accept: application/json

###
# securedEndpoint
# @name weatherforecast
GET {{AspNetCoreIdentity_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{accessToken}}

###
# @name register
POST {{AspNetCoreIdentity_HostAddress}}/register/
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "Abc@123"
}

###
# @name loginCookie
POST {{AspNetCoreIdentity_HostAddress}}/login?useCookies=true
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "Abc@123"
}

###
# @name login
POST {{AspNetCoreIdentity_HostAddress}}/login?useCookies=false
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "Abc@123"
    # "twoFactorCode": "string",
    # "twoFactorRecoveryCode": "string"
}

###

@accessToken = {{login.response.body.accessToken}}
@refreshToken = {{login.response.body.refreshToken}}

# @name refreshToken
POST {{AspNetCoreIdentity_HostAddress}}/refresh
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

###
# @name logout
POST {{AspNetCoreIdentity_HostAddress}}/logout
Content-Type: application/json

{
}

###
# @name confirmEmail
# @prompt userId
# @prompt code
# @prompt changedEmail
GET {{AspNetCoreIdentity_HostAddress}}/confirmEmail
    ?userId={{userId}}
    &code={{code}}
    &changedEmail={{changedEmail}}
Content-Type: application/json

###
# @name resendConfirmationEmail
POST {{AspNetCoreIdentity_HostAddress}}/resendConfirmationEmail
Content-Type: application/json

{
    "email": "{{email}}"
}

###
# @name forgotPassword
POST {{AspNetCoreIdentity_HostAddress}}/forgotPassword
Content-Type: application/json

{
    "email": "{{email}}"
}

###
# @name resetPassword
POST {{AspNetCoreIdentity_HostAddress}}/resetPassword
Content-Type: application/json

{
    "email": "{{email}}",
    "resetCode": "string",
    "newPassword": "string"
}

###
# @name manage2fa
POST {{AspNetCoreIdentity_HostAddress}}/manage/2fa
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    # First run empty json
    # Create QR code from share key, Key Uri Format: `otpauth://totp/YOUR_LABEL:YOUR_EMAIL?secret=YOUR_SHARE_KEY&issuer=Example`
    # Second run 2 first lines
    # "enable": true,
    # "twoFactorCode": "string",
    # "resetSharedKey": true,
    # "resetRecoveryCodes": true,
    # "forgetMachine": true
}

###
# @name getManageInfo
GET {{AspNetCoreIdentity_HostAddress}}/manage/info
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
# @name postManageInfo
POST {{AspNetCoreIdentity_HostAddress}}/manage/info
Content-Type: application/json

{
    "newEmail": "string",
    "newPassword": "string",
    "oldPassword": "string"
}